### ISSUE TITLE
「bldg:Building」の「bldg:class」の読み込みについて

### ISSUE THREAD

**Issue by ejdhplab** [MIERUNE/plateau-qgis-plugin#118]
Github初心者です

プラグイン内の「PLATEAU 3D都市モデルを読み込む」を使わせていただいたのですが、とても使いやすかったです。
ただ、QGISにCityGMLを直接読み込ませた場合と異なり、出力されたレイヤの属性に「bldg:class」が含まれておりませんでした。
「bldg:class」はバス停シェルターやアーケード商店街など上屋だけの建物と通常の建物と区別することができるため、CityGMLを利用した浸水シミュレーション等において重要な要素と考えます。
こちらの属性の読み取りについては今後追加予定はございますでしょうか？
無い場合は追加して頂ければ幸いです。よろしくお願いします。

**Comment by ciscorn** [comment]
@ejdhplab プラグインをご利用頂き、ありがとうございます。

> 出力されたレイヤの属性に「bldg:class」が含まれておりませんでした。

ご報告、大変ありがとうございます。これは意図する動作ではないので確認したところ、単純に `bldg:class` の取扱いが抜けていました。近日中に修正したいと思います。ご報告を頂いて大変助かりました。

**Comment by ciscorn** [comment]
@ejdhplab `bldg:class` に関して修正したものを、QGIS プラグインリポジトリにアップロードいたしました。

数時間中に、バージョン v0.0.5 として利用可能になると思いますので、QGISのプラグイン管理画面からご確認ください。

この度はご報告いただきありがとうございました。

![Untitled](https://github.com/MIERUNE/plateau-qgis-plugin/assets/5351911/1ce6ebb8-6fe9-49ca-b53e-f5ed619cea90)
