### ISSUE TITLE
QGIS Plugin Repository で公開する

### ISSUE THREAD

**Issue by ciscorn** [MIERUNE/plateau-qgis-plugin#76]
一般ユーザがプラグインをzipからインストールすることは推奨されていないし（警告文が2段階くらい出る）、また広く利用されてほしいという要求のうえでも、できれば「QGIS Plugin Repository」からインストールできる状態にしておくのが望ましい。

許可が出たら公開する。

**Comment by kntoshiya** [comment]
公開済みなのでクローズ
